<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a51b5027-5fa0-4efa-8d85-ebba8f93badf</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TechNewsOficialBackend.Application\TechNewsOficialBackend.Application.csproj" />
    <ProjectReference Include="..\TechNewsOficialBackend.Infrastructure\TechNewsOficialBackend.Infrastructure.csproj" />
  </ItemGroup>

</Project>
